app:
    resource: '@AppBundle/Controller/'
    type: annotation

home_page:
    path: /
    defaults: {_controller: AppBundle:Default:index}

map_page:
    path: map/
    defaults: {_controller: AppBundle:Default:map}

places_page:
    path: places/
    defaults: {_controller: AppBundle:Default:places}

place_page:
    path: place/{place}
    defaults: {_controller: AppBundle:Default:place}

remove_place:
    path: place/remove/{place}
    defaults: {_controller: AppBundle:Moderator:removePlace}

edit_place:
    path: place/edit/{place}
    defaults: {_controller: AppBundle:Moderator:editPlace}

messages_page:
    path: /place/{place}/messages
    defaults: {_controller: AppBundle:Default:messages}

addPurchase:
    path: purchase/add/{item}
    defaults: {_controller: AppBundle:Default:addPurchase}

remove_purchase:
    path: place/{place}/purchase/remove/{purchase}
    defaults: {_controller: AppBundle:Default:removePurchase}

markItem:
    path: mark/{item}/place/{place}
    defaults: {_controller: AppBundle:Default:markItem}

unmarkItem:
    path: unmark/{item}/place/{place}
    defaults: {_controller: AppBundle:Default:unmarkItem}

#MODERATOR

removeUserFromPlace:
    path: place/{place}/removeuser/{user}
    defaults: {_controller: AppBundle:Moderator:removeUserFromPlace}

removeItemFromPlace:
    path: place/{place}/removeitem/{item}
    defaults: {_controller: AppBundle:Moderator:removeItemFromPlace}


#FOS

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
