app:
    resource: '@AppBundle/Controller/'
    type: annotation

home_page:
    path: /
    defaults: {_controller: AppBundle:Default:index}

map_page:
    path: map/
    defaults: {_controller: AppBundle:Default:map}