# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.place_voter:
        class: AppBundle\Security\PlaceVoter
        tags:
            - { name: security.voter }

        public: false

    app.item_voter:
        class: AppBundle\Security\ItemVoter
        tags:
            - { name: security.voter }

        public: false
