<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlertRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AlertRepository extends EntityRepository
{
    /**
     * @param User $user
     *
     * @return array
     */
    public function getNotReadNum(User $user)
    {
        return $this->createQueryBuilder('p')
            ->select('COUNT(p.id)')
            ->where('p.user = :user')
            ->andWhere('p.status = :status')
            ->setParameters([
                ':user' => $user,
                ':status' => 1
            ])
            ->getQuery()
            ->getResult()[0][1];
    }
}
