<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PurchaseRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends EntityRepository
{
    /**
     * @param Place $place
     *
     * @return Purchase[]|array
     */
    public function getAllPurchaseByPlace(Place $place)
    {
        $items = $place->getItems();
        $ids = array();

        /** @var Item $item */
        foreach ($items as $item) {
            $ids[] = $item->getId();
        }

        $purchase = $this->getEntityManager()
            ->getRepository(Purchase::class)
            ->findBy(array('item' => $ids));

        return array_reverse($purchase);
    }

    /**
     * @param Item $item
     *
     * @return \Doctrine\ORM\Query
     */
    public function getLatestPurchaseQuery(Item $item)
    {
        return $this->createQueryBuilder('p')
            ->where('p.item = :item')
            ->setParameters([
                ':item' => $item
            ])
            ->orderBy('p.date', 'ASC')
            ->getQuery();
    }
}
