<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PurchaseRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends EntityRepository
{
    /**
     * @param $place
     * @return Purchase[]|array
     */
    public function getAllPurchaseByPlace($place)
    {
        $items = $place->getItems();
        $ids = array();

        foreach ($items as $item) {
            $ids[] = $item->getId();
        }

        $purchase = $this->getEntityManager()
            ->getRepository(Purchase::class)
            ->findBy(array('item' => $ids));

        return $purchase;
    }
}
